name: ✨ Feature Request
description: Suggest a new feature or enhancement for LPU Live
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to see in LPU Live.
      placeholder: I would like to have...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Why do you need this feature?
      description: Explain how this feature would help you and what problem it solves.
      placeholder: This would help me...
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Screenshots/Examples (Optional)
      description: If applicable, add mockups, screenshots, or examples from other apps that demonstrate your idea.
      placeholder: Paste or drag images here

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or information about the feature request here.
      placeholder: Any additional information that might be helpful

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested before
          required: true
